### ISSUE TITLE
Error: Cannot find module '../../firebaseCredentials.json'

### ISSUE THREAD

**Issue by ravinderpoonia07** [opentok/interactive-broadcast-api#21]
Hi Team,

I tried to compile ibs-api and getting the below error. Now as I can see there is no file **firebaseCredentials.json** in the project folder. Also, all the information related to firebase has been defined in the .env files. Can you please have a look and help me out with this. Thanks. 

yarn run v1.22.4
$ gulp serve
[08:24:33] Failed to load external module @babel/register
[08:24:33] Requiring external module babel-register
[08:24:33] Using gulpfile /var/www/html/interactive-broadcast-api/gulpfile.babel.js
[08:24:33] Starting 'clean'...
[08:24:34] Finished 'clean' after 27 ms
[08:24:34] Starting 'serve'...
[08:24:34] Starting 'copy'...
[08:24:34] Starting 'babel'...
[08:24:34] Finished 'serve' after 67 ms
[08:24:36] Finished 'copy' after 2.45 s
[08:24:37] Finished 'babel' after 3.48 s
[08:24:37] Starting 'nodemon'...
[08:24:37] Finished 'nodemon' after 65 ms
[08:24:37] [nodemon] 1.17.5
[08:24:37] [nodemon] to restart at any time, enter `rs`
[08:24:37] [nodemon] watching: *.*
[08:24:37] [nodemon] starting `node dist/index.js`
module.js:549
    throw err;
    ^

Error: Cannot find module '../../firebaseCredentials.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/interactive-broadcast-api/dist/server/services/firebase.js:11:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
[08:24:38] [nodemon] app crashed - waiting for file changes before starting...

**Comment by rhainer** [comment]
Take a look at the Configuration Settings section of the README file. There are some instructions for configuring Firebase there.

**Comment by ravinderpoonia07** [comment]
Thanks @rhainer . Yes I am following all the instructions given in READ.md. I have defined all the firebase parameter in **.env** and **config/config.js**.  Can you please help me out with this or any other documentation that I can follow to configure both API backend and Frontend server. Looking forward to hearing from you.

**Comment by kewlcherry** [comment]
This file has to be generated seperately, login to firebase and go to project setting -> serviceaccounts and click generate private key

It will look like below ( don't use the below one as is )
https://github.com/opentok/interactive-broadcast-api/blob/602d42ef35843f16ecd82a53a726676cbb18af87/firebaseCredentials.json
