### ISSUE TITLE
How can I generate a default admin user?

### ISSUE THREAD

**Issue by sajjadsaleem** [opentok/interactive-broadcast-api#26]
I have installed the API and it look like working, but, how can I generate a default admin, which could generate token etc and create sessions etc?

**Comment by rhainer** [comment]
Take a look at https://github.com/opentok/interactive-broadcast-api/blob/master/server/scripts/create-user.js. I believe that is a script that is intended to be used to create the first Admin user. From then on, you can create new users via the UI.

**Comment by sajjadsaleem** [comment]
ok thanks for your help, I am able to create a user.

It is not letting me login though probably due to the following ajax request

OPTIONS http://example.com/api/auth/token
It responds with [HTTP/1.1 401 Unauthorized 468ms]

Can you please help me resolve this as well?

**Comment by sajjadsaleem** [comment]
I installed ssl and made some changes in URL

Now, the response is like this.

XHR POSThttps://example.com//api/auth/token
[HTTP/1.1 401 Unauthorized 827ms]
    	
    message	"Unauthorized"
    stack	"Error: No authorization token was found\n at APIError.ExtendableError (/home/sysadmin/server/helpers/APIError.js:14:11)
at new APIError (/home/sysadmin/server/helpers/APIError.js:30:85)\n at /home/sysadmin/conf2/config/express.js:71:22
at Layer.handle_error (/home/sysadmin/conf2/interactive-broadcast-api/node_modules/express/lib/router/layer.js:71:5)
at trim_prefix (/home/sysadmin/conf2/interactive-broadcast-api/node_modules/express/lib/router/index.js:310:13)\n at /home/sysadmin/co…dcast-api/node_modules/express/lib/router/index.js:330:12)
at next (/home/sysadmin/conf2/interactive-broadcast-api/node_modules/express/lib/router/index.js:271:10)
at Layer.handle_error (/home/sysadmin/conf2/interactive-broadcast-api/node_modules/express/lib/router/layer.js:67:12)\n at trim_prefix (/home/sysadmin/conf2/interactive-broadcast-api/node_modules/express/lib/router/index.js:310:13)
at /home/sysadmin/conf2/interactive-broadcast-api/node_modules/express/lib/router/index.js:280:7"

**Comment by ggoldens** [comment]
@sajjadsaleem have you fixed this issue already?
